### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by gcstang** [pitaj/wengit#4]
electron main-riot.js
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/gcollins/GitRepositories/3rdparty/wengit/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gcollins/GitRepositories/3rdparty/wengit/main-riot.js:3:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by pitaj** [comment]
This project is inactive and unfinished.
